### ISSUE TITLE
Turkey zone support

### ISSUE THREAD

**Issue by leventkantaroglu** [poqueque/random_name_generator#1]
Hi, 
When I was looking for a Turkish name generator, I saw this package. 

I want to contribute Turkish support for this package.
If you agree, I will send a pull-request

**Comment by poqueque** [comment]
Of course! Please send a pull-request

**Comment by leventkantaroglu** [comment]
I sent it ✌️ 
https://github.com/poqueque/random_name_generator/pull/2

**Comment by poqueque** [comment]
Version 1.1.0 published containing PR #2
